services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    env_file:
      - 'compose/aws.env'
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/lib/localstack'
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566/_localstack/health']
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - identity-services

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    restart: always
    networks:
      - identity-services

  mongodb:
    image: mongo:6.0.13
    networks:
      - identity-services
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    restart: always

  identity-service-handler:
    build:
      context: ./
      target: ${NODE_ENV:-development}
    platform: linux
    healthcheck:
      test: ['CMD', 'node', '/home/node/scripts/healthcheck.js']
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s
    ports:
      - '${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}'
    links:
      - 'localstack:localstack'
      - 'redis:redis'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
      test-site:
        condition: service_healthy
    env_file:
      - path: 'compose/aws.env'
        required: true
      - path: 'compose/identity-service-handler.env'
        required: false
    environment:
      PORT: ${FRONTEND_PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: ${USE_SINGLE_INSTANCE_CACHE:-true}
      USE_FAKE_EXTERNAL_API: ${HELPER_USE_FAKE_CLIENT:-true}
      HELPER_BASEURL: ${HELPER_BASEURL:-http://identity-service-helper:8080}
      HELPER_API_KEY: ${HELPER_API_KEY:-test}
      B2C_CLIENT_ID: ${B2C_CLIENT_ID:-stub-client-id}
      B2C_CLIENT_SECRET: ${B2C_CLIENT_SECRET:-stub-client-secret}
      B2C_SERVICE_ID: ${B2C_SERVICE_ID:-stub-service-id}
      B2C_DISCOVERY_URL: ${B2C_DISCOVERY_URL:-https://test-site:3005/b2c/.well-known/openid-configuration}
      B2C_REDIRECT_URL: ${B2C_REDIRECT_URL:-https://identity-service-handler:3000/sso}
      DEBUG: ${DEBUG:-oidc-provider:*}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS:-}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}
      OIDC_SIGNING_CERT: ${OIDC_SIGNING_CERT:-LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVlRENDQXVDZ0F3SUJBZ0lSQUtFNjBNY0hzQ0l4TTRTTnpmNlNaV1l3RFFZSktvWklodmNOQVFFTEJRQXcKZ2E4eEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEZDTUVBR0ExVUVDd3c1YldGNApZbXhoWkdWdUxXTnNZWEpyUUUxaGVITXRUV0ZqUW05dmF5MUJhWEl1Ykc5allXd2dLRTFoZUNCQ2JHRmtaVzR0ClEyeGhjbXNwTVVrd1J3WURWUVFEREVCdGEyTmxjblFnYldGNFlteGhaR1Z1TFdOc1lYSnJRRTFoZUhNdFRXRmoKUW05dmF5MUJhWEl1Ykc5allXd2dLRTFoZUNCQ2JHRmtaVzR0UTJ4aGNtc3BNQjRYRFRJMk1EVXdOVEV6TVRFMApNVm9YRFRJNE1EZ3dOVEV6TVRFME1Wb3dZekVuTUNVR0ExVUVDaE1lYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwCklHTmxjblJwWm1sallYUmxNVGd3TmdZRFZRUUxEQzl0WVhoaWJHRmtaVzR0WTJ4aGNtdEFUV0Y0Y3kxQmFYSXUKYkdGdUlDaE5ZWGdnUW14aFpHVnVMVU5zWVhKcktUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFNV0I2TWU5Ly9rS3ZOMzdhWks5VysxTWdCTWFtMVZUM1lDa2VndXd0YkxacEpIV21odGRMeWVYCkZ1b25zUDFEY0RGek42RFZMdDRVTzlsMlpYQjRhYjhpeVVMTmNlWkZlSGo0NGJ3NWFvRStVVFE0M2JSeEdJMWkKWHc1MmRCamNReWRZSG9YZk12bnNHMWNoTjZiSTNHSEhwTEJ0alFEL3FuU0xRRjIwbzBoaWtHZWJ3MTlscHkwTAptUk41ZElKMFdwNTIyeTU2SlhoakJwWWJEbU5ZV05yVk9Gak1pWkkvL1B5aVVtY3E0SEc3c2NxaHZrSC85a0ZYClBCWUpsRmtwd3hEQzBXVDNzeGVXL3JRQWtPclQ0MkRYQVF0dVM5UXFMQ29HNFBSNHo4b2pmVzN0ZW5UZzFvWW0KOVhnMHF4b3lrdk5FMXJIcnBMNG14czNtN2ZXZHQxc0NBd0VBQWFOYU1GZ3dEZ1lEVlIwUEFRSC9CQVFEQWdXZwpNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUI4R0ExVWRJd1FZTUJhQUZDdkYrcC9pZ005UGZmRGdCZGR3CnBkc0lROFllTUJBR0ExVWRFUVFKTUFlQ0JXeHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCZ1FBTytqY1cKbUx6enQrVE5FSnQ5V2hWZmxoM2s0WmRKWTB5VHQ4S1puVlBXbmxERHBSdGFFMEtsQ29SZm1FOWV1eWQ1K3dacwp4VkhKdVdaOHpETHpvWWJIdDhMclBQeGwrcUJEQzkzandaVTNhYnVRR1Bra0dZbmZlajh6ZTQ1c3lCc1RqeGNsCkV5bnFvQlZidWlEUEUwMWNSZ1pCNDdocUNLc29TRzlhN1BianQzMitMWkJIbHJXQkwxeXVPRlV4aGdDTUt0Z0oKdFAvNXBzMzRaMFJ1QktzNkltNGxxSS9RMHdEUlRtZ2JxWC8yMFFSZ1hnUVhuNk9INkNJMDhlNnl0WnZDeURrQwo3TWNsdmRRdE5iVXIreXMrOGVNYWNpeEtyL0VkdVMvekYwWjkwUDNBMzB1RzZIeWFxMmZXTDE3TkxHcUlCdm1MCkJxakdLdFFwRXFwNjMxOWZCdTNuZG5nMWNPOTNzL3AyMUZhY2JsNm9LVVpQdFpzV3hLM2N2ZXN1OGpmTUJDZjQKVEZYUXNDdFhQVlZTT0VrZDRGTEx1eDIyb052bWU5NFNlS0ZTS1VYU0Z4L3E0ZWZndmMvbEw3U05zUlZONVZmWQpKTGZzd1Q1TWV3blF6ek9DQWhjRVB2ZzlyVXhxbU8wQWx6YmF4QjdGdExrNXJvODZvU3EzUGpwSDVFMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=}
      OIDC_SIGNING_KEY: ${OIDC_SIGNING_KEY:-LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRREZnZWpIdmYvNUNyemQKKzJtU3ZWdnRUSUFUR3B0VlU5MkFwSG9Mc0xXeTJhU1IxcG9iWFM4bmx4YnFKN0Q5UTNBeGN6ZWcxUzdlRkR2WgpkbVZ3ZUdtL0lzbEN6WEhtUlhoNCtPRzhPV3FCUGxFME9OMjBjUmlOWWw4T2RuUVkzRU1uV0I2RjN6TDU3QnRYCklUZW15TnhoeDZTd2JZMEEvNnAwaTBCZHRLTklZcEJubThOZlphY3RDNWtUZVhTQ2RGcWVkdHN1ZWlWNFl3YVcKR3c1aldGamExVGhZekltU1AvejhvbEpuS3VCeHU3SEtvYjVCLy9aQlZ6d1dDWlJaS2NNUXd0Rms5N01YbHY2MApBSkRxMCtOZzF3RUxia3ZVS2l3cUJ1RDBlTS9LSTMxdDdYcDA0TmFHSnZWNE5Lc2FNcEx6Uk5heDY2UytKc2JOCjV1MzFuYmRiQWdNQkFBRUNnZ0VBVmJVZnBsb1JrK2x3ZHlYc05PVGVXUFliRis4eVhBOVdMa1p4dmRQenJVYWMKRHp0Z3lhSWczZDNIY0ZwRUNFdDFDc2gwYWVOSkFNOG4vNkRNdVVkUG9FV0FyL0FHVHNaejFvOHVLaWVDUzg2VwpuNEpUMTBOQ3c4dmQ4eUU5RlRLMEk0VXVUYXJEYk1ma1AyV25TRVdldVFIUk9reDM1V2lNK0NFYmorNWM4d0lyCmQ1MWNPQklTelN1aTJXeEFlYll4b3JLQ1ZHTjdYZGc3dlY4RXJtTG1aSUIyQlhmRzFnYzd1cVVlN0pQRjlIRUYKZjVMcHA2dDA4cUtXOU1uU085Ti9VK2FBTFZZdzdiZlpRcXZJRzFtWnM1QnI1SlJlQmw4N1djSGNYQ2ZrcEVqcQpTaHNRd2NkdCt4cVRoZ2Q1Nkh6WjRHOFZQMzZ4TEV1Q2M1VmlJQVY3alFLQmdRRGt1UE8xL0t5bDFQamVtMkJlClc3d0F1T0l6c1pabXJWTjlkYUxoRWw4S0pUbWc1WEZZZzNXTEFVTGpkYXlaTlBKMzJjYytHeVhWZTh5alZ4a20KQ1JxamhmWklEQjlLdnBCWXFQNmxqTTJqWm15NVhqNSsram9mc3Y4UjhSZVU0Tkh5MEJ6eis5UjVSWkk0UEJRQgpteDNwTU9EalpETmF3YkJSeERUYzgyWEtWd0tCZ1FEZEQvRkNUblA1TU9CY0puUHdzMWgxZURYYW9aUERteW1YCkJSSWpxYmxibXVOUTNHa3A4SFdia05UazZEVFZqeXNucHo1NFRCS1JGNlBMdEc2T1h0ZVJsRlZLeGkzMTZXUDgKYS8xdklyQlE1azhlUHk1R0E4VW9vcTFjSUVic3hHZzNPdk9nektCTExCMk5oby9BUDRsTlY1cndkNmQ2SVpRNwpiVkUvakRCZ25RS0JnQ3JFSWwyZTF6RlN0dzM0ZzNaaE5LLzE0ZVhFaU5pK0ErUnJnSDhSRGxBNVVhTXlBNVdIClR3MGt1VHNLbjdFdDQwQmhxZzJFeWZnMjQ3YU83SmJlRU9zT2UxUlJYL0I3M1VXV283YVVzMGFnT2lnVzVSeWMKOFExSVRNVXdEVGE3S3NaNS8wL25nSDBFY3lpc294a0J4Zi82TWJLUzQ3OU9oQWRsNW5TQjFrQ1ZBb0dBUHA0NQpkTkxNUHhYOU41MGMwbDI2L090a05kMzNBVDErZG16VlNvelZHSUd6U2tCaythQkhjQjJDY0tUbDhtaHZqUGZ1CjFoeVdWY3NnZHA5UmdicVR6WVQ2OUFkWEZZVmE4VEdWeEZsTElGOWNvZkM3cHRHQ2s1UWhEeXVGYTZQbThWNGQKakxycDNPRk9MYnlrRTR6cjA2Q3hIdFNGK0M1eTByS1FoVE9zc0hFQ2dZQWhlMWRaNk85SWQrVktkZ2MvYkJVMwpRa0ZpbDhXVlZHTnZnVzl5dXBhK0hwb3AzMStWS01MVk5DQ1ZGVU40dXBQY0hqc0dMVmdSYUdNNjdmTjJIajZaCkNJUGJDc2F2cm85RTR5Qm81OUxFbW1qZDFmU05QN1lZMEtMTXhkZGxnNy9VUTVyRnczRllrZ2hSNGdwWWNzQk8KZ2x2MXVySlllTFJqT29ZNG5aVmk1Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K}
      SESSION_COOKIE_PASSWORD: ${SESSION_COOKIE_PASSWORD:-v9yg3NU08bnsAco724GAK5hStUX8Hqn9}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-true}
      TLS_ENABLED: ${TLS_ENABLED:-true}
      BROKER_BASE_URL2: ${BROKER_BASE_URL2:-https://identity-service-handler.dev.cdp-int.defra.cloud/}
      BROKER_REDIRECT_URL2: ${BROKER_REDIRECT_URL2:-https://fakelocal}
    networks:
      - identity-services

  test-site:
    image: node:22
    working_dir: /repo/test-site
    command: sh -c "npm install && npm run docker:dev"
    healthcheck:
      test: ['CMD', 'node', '/repo/test-site/scripts/healthcheck.js']
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s
    ports:
      - '3005:3005'
    volumes:
      - ./:/repo
      - test-site-modules:/repo/test-site/node_modules
    environment:
      PORT: 3005
      NODE_ENV: development
      SESSION_COOKIE_PASSWORD: ${SESSION_COOKIE_PASSWORD:-v9yg3NU08bnsAco724GAK5hStUX8Hqn9}
      HELPER_BASEURL: ${HELPER_BASEURL:-http://identity-service-helper:8080}
      HELPER_API_KEY: ${HELPER_API_KEY:-test}
      STUB_B2C_EXTERNAL_BASE: ${STUB_B2C_EXTERNAL_BASE:-https://test-site:3005/b2c}
      STUB_B2C_INTERNAL_BASE: ${STUB_B2C_EXTERNAL_BASE:-https://test-site:3005/b2c}
    networks:
      - identity-services

volumes:
  mongodb-data:
  test-site-modules:

networks:
  identity-services:
    external: true
