name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: |
          npm ci
          npm run build:frontend
          npm run format:check
          npm run lint
          npm test

      - name: Analyze with SonarQube
        if: github.actor != 'dependabot[bot]'
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0 run `git ls-remote https://github.com/SonarSource/sonarqube-scan-action` to get the sha1 list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
